name: Build assignemnts.pdf document

on:
  push:
    paths:
      - 'assignments/**'
      - '.github/workflows/build_assignments.yml'
  pull_request:
    branches:
      - 'current'
      - 'future/**'

jobs:

  build_assignments:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref_name == 'current' || startsWith(github.ref_name, 'future/')
    permissions: write-all
    steps:

      - name: Initialize
        uses: actions/checkout@v4

      - uses: kostrykin/build-latex-document-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: assignments
          document_filename: assignments.pdf
          sources: |
            session0.tex
            session1.tex
            session2.tex
            session3.tex
            session4.tex
            session5.tex
            assignments.tex
